config/routes.rb
Rails.application.routes.draw do
    resources :products do
        scope module: :product do
            resources :bids
        end
    end
    resources :myitems



    devise_for :users
    devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
    end
    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: "home#index"
end

app/views/shared/_navbar.html.erb
<% name = current_user.present? ? current_user.email : 'Guest' %>
<% name2 = current_user.present? ? current_user.username : 'Guest' %>
<nav class="navbar navbar-expand-lg navbar-purple">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Lomax Technologies</a><br>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
                <li class="nav-item" >
                    <%= link_to 'Store', products_path, class: 'nav-link'%>
                </li>
            <% if user_signed_in? %>

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= name2 %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to 'Add product', new_product_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'My products', myitems_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item'%></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item'%></li>

            </ul>
            </li>

            <% else %>

                <li class="nav-item" >
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link'%>
                </li>
            <% end %>
        </ul>
        </div>
    </div>
</nav>