config/routes.rb
Rails.application.routes.draw do
    resources :products do
        scope module: :product do
            resources :bids
        end
    end
    resources :myitems



    devise_for :users
    devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
    end
    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
    #validate :check_file_presence
    validate :expiration_date_cannot_be_in_the_past
    belongs_to :user, foreign_key: 'users_id' 
    has_one_attached :image
    has_many :product_bid, dependent: :restrict_with_error, class_name: 'Product::Bid', foreign_key: 'products_id'

    validates :name, presence: true, allow_blank: false
    validates :description, presence: true, allow_blank: false
    validates :price, presence: true, allow_blank: false
    validates :limit_date, presence: true, allow_blank: false
    
    validates :price, :numericality => { :greater_than_or_equal_to => 0 }
    
    
    def check_file_presence
        errors.add(:image, "file has not been attached") unless image.attached?
    end
    
    def expiration_date_cannot_be_in_the_past
        if limit_date < DateTime.now
            errors.add(:limit_date, "can't be in the past")
            raise ActiveRecord::Rollback 
        end
    end 

end

app/models/product/bid.rb
class Product::Bid < ApplicationRecord
    
    after_save :valid_time
    belongs_to :user, foreign_key: 'users_id' 
    belongs_to :product, foreign_key: 'products_id'
    after_save :bid_enough
    before_save :bid_enough_actual

    validates :amount, presence: true, allow_blank: false

    protected
    # Validates the bid amount
    def bid_enough
        actual_bid = self.product.price
        max_amount = Product::Bid.maximum('amount')
        if amount <= self.product.price
            puts "***********************", actual_bid, "************************"
            errors.add(:base, "Bid must be above the actual bid.")
            raise ActiveRecord::Rollback 
        else
            puts "Felicidades"
        end
    end

    protected
    def bid_enough_actual
        #max_amount = Product::Bid.maximum('amount')
        
        @max_amount = Product::Bid.where(products_id: self.product.id).maximum("amount")
        if @max_amount.nil?
            @max_amount = 0
        end
        if amount <= @max_amount
            puts "***********************", @max_amount, "************************"
            errors.add(:base, "Bid must be above the actual bid.")
            raise ActiveRecord::Rollback 
        else
            puts "Felicidades"
        end
    end

    protected
    def valid_time
        deadline = self.product.limit_date

        if DateTime.now > deadline
            errors.add(:limit_date, "has passed. This product is no longer available.")
            raise ActiveRecord::Rollback 
        end


    end

    
end

app/models/product/review.rb
class Product::Review < ApplicationRecord
end

app/controllers/product/bids_controller.rb
class Product::BidsController < ApplicationController
    before_action :set_product_bid, only: %i[ show edit update destroy ]
    
    # GET /product/bids or /product/bids.json
    def index
        #@product_bids = Product::Bid.all
        @product_bids = Product::Bid.order(:amount).where(products_id: params[:product_id])
        @product_imagen = Product.find_by_id(params[:product_id])
    end
    
    # GET /product/bids/1 or /product/bids/1.json
    def show
        @productshow = Product.find_by_id(params[:product_id])
        
    end
    
    # GET /product/bids/new
    def new
        @product_bid = Product::Bid.new
        @productnew = Product.find_by_id(params[:product_id])
        @product_bids_max = Product::Bid.order(:amount).where(products_id: params[:product_id])
        @product_bids = Product::Bid.order(:amount).where(products_id: params[:product_id]).last
    end
    
    # GET /product/bids/1/edit
    def edit
        @product_imagen_edit = Product.find_by_id(params[:product_id])
    end
    
    # POST /product/bids or /product/bids.json
    def create
        @product_bids_max = Product::Bid.order(:amount).where(products_id: params[:product_id])
        @product_bids = Product::Bid.order(:amount).where(products_id: params[:product_id]).last
        @product_bid = Product::Bid.new(product_bid_params)
        @product_bid.product = Product.find_by_id(params[:product_id])
        @product_bid.user = current_user
        @productnew = Product.find_by_id(params[:product_id])
        if user_signed_in? 
            respond_to do |format|
                if @product_bid.save
                    format.html { redirect_to new_product_bid_url, notice: "Congratulations! Your bid has been placed successfully." }
                    format.json { render :show, status: :created, location: @product_bid }
                else
                    format.html { render :new, status: :unprocessable_entity }
                    format.json { render json: @product_bid.errors, status: :unprocessable_entity }
                end
            end
        else
            respond_to do |format|
                format.html { redirect_to new_product_bid_url, alert: "You must be Signed in to make a bid." }
                format.json { head :no_content }
            end
        end
    end
    
    # PATCH/PUT /product/bids/1 or /product/bids/1.json
    def update
        respond_to do |format|
            if @product_bid.update(product_bid_params)
                format.html { redirect_to @product_bid, notice: "Bid was successfully updated." }
                format.json { render :show, status: :ok, location: @product_bid }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @product_bid.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /product/bids/1 or /product/bids/1.json
    def destroy
        @product_bid.destroy
        respond_to do |format|
            format.html { redirect_to product_bids_url, notice: "Bid was successfully destroyed." }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_bid
        @product_bid = Product::Bid.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def product_bid_params
        params.fetch(:product_bid, {}).permit(:amount)
    end

end

app/controllers/product/reviews_controller.rb
class Product::ReviewsController < ApplicationController
  before_action :set_product_review, only: %i[ show edit update destroy ]

  # GET /product/reviews or /product/reviews.json
  def index
    @product_reviews = Product::Review.all
  end

  # GET /product/reviews/1 or /product/reviews/1.json
  def show
  end

  # GET /product/reviews/new
  def new
    @product_review = Product::Review.new
  end

  # GET /product/reviews/1/edit
  def edit
  end

  # POST /product/reviews or /product/reviews.json
  def create
    @product_review = Product::Review.new(product_review_params)

    respond_to do |format|
      if @product_review.save
        format.html { redirect_to @product_review, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @product_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/reviews/1 or /product/reviews/1.json
  def update
    respond_to do |format|
      if @product_review.update(product_review_params)
        format.html { redirect_to @product_review, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @product_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/reviews/1 or /product/reviews/1.json
  def destroy
    @product_review.destroy
    respond_to do |format|
      format.html { redirect_to product_reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_review
      @product_review = Product::Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_review_params
      params.fetch(:product_review, {})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]
    
    # GET /products or /products.json
    def index
        # p Product.all.order(:id).to_sql
        # p "*************Index para la vista VUE****************"
        #@products = Product.all
        #@x = Product::Bid.order(:created_at).last
        
        # @products = Product.all.order(:id)
        
        # @products.each do |product|
        # max_bind = Product::Bid.where(products_id: product.id).order(:amount).last
        
        # product.attributes.merge({
        # max_bind: max_bind
        # })
        # end
        # debugger
        
        @products = Product.all.order(:id)

        @products.map do |product|
            @major_bid = Product::Bid.order(:amount).where(products_id: product.id).last
        end

        #puts @products.ids , "Alo alo alo alo aol alo alo a lo alo alo"
        #puts @major_bid.amount , "Alo alo alo alo alo alo alo alo alo"
        #puts @products.ids , "Alo alo alo alo aol alo alo a lo alo alo"
        #render json: @products
    
    end
    
    def mysales
        @items = Product.where(users_id: params[:user_id])
    end
    
    # GET /products/1 or /products/1.json
    def show
    end
    
    # GET /products/new
    def new
        @product = Product.new
    end
    
    # GET /products/1/edit
    def edit
        
    end
    
    # POST /products or /products.json
    def create
        @product = Product.new(product_params)
        @product.user = current_user
        respond_to do |format|
            if @product.save
                format.html { redirect_to @product, notice: "Product was successfully created." }
                format.json { render :show, status: :created, location: @product }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @product.errors, status: :unprocessable_entity }
            end
        end
    end

    
    # PATCH/PUT /products/1 or /products/1.json
    def update
        respond_to do |format|
            if @product.update(product_params)
                format.html { redirect_to myitems_path, notice: "Product was successfully updated." }
                format.json { render :show, status: :ok, location: @product }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @product.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /products/1 or /products/1.json
    def destroy
        #@product.destroy
        #respond_to do |format|
        #    format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
        #    format.json { head :no_content }
        #end
        if @product.destroy
            flash[:notice] = "Action performed successfully"
            redirect_to myitems_path      
          else
            flash[:alert] = "You can't delete a product that already has bids from users."
            redirect_to myitems_path
          end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
        @product = Product.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def product_params
        params.fetch(:product, {}).permit(:name, :description, :price, :limit_date, :image)
    end
end

app/helpers/product/bids_helper.rb
module Product::BidsHelper
end

app/helpers/product/reviews_helper.rb
module Product::ReviewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/product/bids/_form.html.erb
<%= form_with(model: product_bid) do |form| %>
    <% if product_bid.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(product_bid.errors.count, "error") %> prohibited this product_bid from being saved:</h2>

        <ul>
            <% product_bid.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="col-4 offset-2">

        <div class="input-group input-group-bid mb-3">
            <%= form.label :amount, class:"input-group-text" %>
            <%= form.text_field :amount, class:"form-control" %>
        </div>

        <div class="button-bid">
            <div class="actions">
                <%= form.submit class: "button btn btn-primary btn-lg" %>
            </div>
        </div>
        
    </div>

<% end %>

app/views/product/bids/edit.html.erb
<h1>Editing Product Bid</h1>

<%= render 'form', product_bid: @product_bid %>

<%= link_to 'Show', @product_bid %> |
<%= link_to 'Back', product_bids_path %>

app/views/product/bids/index.html.erb
<p id="notice"><%= notice %></p>

<div class="view-title">
    <h1>Bids received</h1>
    <span><h1><%= image_tag(@product_imagen.image, class:'thumbnail-bid-preview') %></h1></span>
</div>
<% if user_signed_in? %>
<div class="bid-actions-back">
    <%= link_to '<i class="fas fa-chevron-circle-left fa-3x"></i>'.html_safe, myitems_path %>
</div>

<% end %>


<table class="table table-hover table-striped">
    <thead class="table-purple">
        <tr>
            <th class="">ID</th>
            <th class="">User</th>
            <th class="">Amount ($)</th>
            <th class="">Deadline</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @product_bids.each do |product_bid| %>
            <tr>
                <td class=""><%= product_bid.id %></td>
                <td class=""><%= product_bid.user.username %></td>
                <td class=""><%= product_bid.amount %></td>
                <td class=""><%= product_bid.created_at %></td>
                <td><%= link_to '<i class="fas fa-eye icon"></i>'.html_safe, product_bid_url(:id => product_bid.id) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<!--%= link_to 'New Product Bid', new_product_bid_path %>-->

app/views/product/bids/new.html.erb
<h1 class="view-title">New Bid</h1>
<div class="bid-actions-back">
    <%= link_to '<i class="fas fa-chevron-circle-left fa-3x"></i>'.html_safe, products_path %>
</div>
<div class="bid-container">
    <div class="bid-details">
        <p>Product: <%=@productnew.name %></p>
        <p>Description: <%=@productnew.description %></p>
        <p>Base price: <%=@productnew.price %> USD</p>
        
        <% if @product_bids.nil?  %>
            
        <% else %>
            <p><strong>Major bid: <%=@product_bids.amount %> USD</strong></p>
		    <p><strong>By: <%=@product_bids.user.username %></strong></p>
        <% end %>
        <p><strong>Deadline: <%=@productnew.limit_date %> </strong></p>

        <% if DateTime.now > @productnew.limit_date %>
            <p><strong>Winner: <%=@product_bids.user.username %></strong></p>
            <p class="passedBid">We are sorry, this product is no longer <br> available. Please comeback later.</p>
        <% else %>
            <p class="inProgressBid">In progress!</p>
        <% end %>
        
        
    </div>
    <span><%= image_tag(@productnew.image, class:'bid-thumbnail') %></span>
</div>

<%= render 'form', product_bid: @product_bid %>



<div class="bid-actions">
    <%= link_to 'Bids history', product_bids_path %>
</div>

app/views/product/bids/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_bid_path(@product_bid) %> |
<%= link_to 'Back', product_bids_path %>