config/routes.rb
Rails.application.routes.draw do
    resources :products do
        scope module: :product do
            resources :bids
        end
    end
    resources :myitems



    devise_for :users
    devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
    end
    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: "home#index"
end

app/controllers/myitems_controller.rb
class MyitemsController < ApplicationController
    def index
        @items = Product.where(users_id: current_user.id)
    end
end

app/helpers/myitems_helper.rb
module MyitemsHelper
end

app/views/myitems/index.html.erb
<h1 class="view-title">My items for sale</h1>
<div class="profilePicture">
    <img src="https://cdn.pixabay.com/photo/2017/06/13/12/53/profile-2398782_1280.png" 
    alt="Cheetah!" style="width:150px;height:150px;" class="center"/>
</div>
<div class="bid-actions-back">
    <%= link_to '<i class="fas fa-chevron-circle-left fa-3x"></i>'.html_safe, products_path %>
</div>
<table class="table table-hover table-striped">
  <thead class="table-purple">
    <tr>
        <th class="">ID</th>
        <th class="">Name</th>
        <th class="">Description</th>
        <th class="">Price</th>
        <th class="">Product</th>
        <th class="">Deadline</th>
        <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
        <% @items.each do |item| %>
            <tr>
                <td class="align-middle"><%= item.id %></td>
                <td class="align-middle"><%= item.name %></td>
                <td class="align-middle"><%= item.description %></td>
                <td class="align-middle"><%= item.price %></td>
                <td class="align-middle"><%= image_tag(item.image, class:'thumbnail') %></td>
                <td class="align-middle"><%= item.limit_date%></td>
        
                <td class="align-middle"><%= link_to '<i class="fas fa-eye icon fa-3x"></i>'.html_safe, product_bids_path(item) %></td>
                <td class="align-middle"><%= link_to '<i class="far fa-edit fa-3x"></i>'.html_safe, edit_product_path(item) %></td>
                <td class="align-middle"><%= link_to '<i class="fas fa-trash-alt fa-3x"></i>'.html_safe, item, method: :delete, data: { confirm: 'Are you sure?' } %></td>

            </tr>
        <% end %>
    </tbody>
</table>

<br>